#!/usr/bin/env python

import pycommand


class $classname(pycommand.CommandBase):
    '''description of the program, used below as __doc__'''
    usagestr = 'usage: $name [options]'
    description = __doc__
    optionList = (
        ('help', ('h', False, 'show this help information')),
        # ('file', ('f', '<filename>', 'use specified file')),
        # ('version', ('', False, 'show version information')),
    )

    def run(self):
        if self.flags.help:
            print(self.usage)
            return 0
        # elif self.flags.version:
        #     print('Python version ' + sys.version.split()[0])
        #     return 0
        # elif self.flags.file:
        #     print('filename = ' + self.flags.file)
        #     return 0

        print('Program completed. Try adding "--help"')

if __name__ == '__main__':
    pycommand.run_and_exit($classname)
